### ISSUE TITLE
Content Security Policy violation

### ISSUE THREAD

**Issue by Axxon** [ritesh83/ember-cli-jstree#11]
Hello and sorry if that issue have not a place here. I installed the addon with npm and bower and tried a minimal test. In my package.json ```"ember-cli-jstree": "yectep/ember-cli-jstree#master"```
I just have for the moment a folder icon displayed on my menu page and this message on my terminal. Please, could you tell me how to fix that ?

```
Content Security Policy violation: {"csp-report":{"document-uri":"http://localhost:4200/category","referrer":"http://localhost:4200/category","violated-directive":"default-src 'none'","effective-directive":"child-src","original-policy":"default-src 'none'; script-src 'self' 'unsafe-eval' localhost:35729 0.0.0.0:35729; font-src 'self'; connect-src 'self' ws://localhost:35729 ws://0.0.0.0:35729 http://0.0.0.0:4200/csp-report; img-src 'self'; style-src 'self'; media-src 'self'; report-uri http://0.0.0.0:4200/csp-report;","blocked-uri":"blob","source-file":"http://localhost:4200/assets/vendor.js","line-number":73749,"column-number":23813,"status-code":200}}
```

into Chrome console:
```
[Report Only] Refused to create a child context containing 'blob:http%3A//localhost%3A4200/84fd7dff-2964-4ea6-b181-***' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'child-src' was not explicitly set, so 'default-src' is used as a fallback.
```

**Comment by yectep** [comment]
This doesn't seem to be an issue related to this addon. It seems to be a CORS error relating to the livereload websocket...

If you remove the addon from your package.json it should still be there. At least it does for me on CLI v0.2.3.

**Comment by Axxon** [comment]
Thanks for your quick return, here what i do to resolve the problem with security policy (without to know excactly what i do ...).
Inside config/environment.js:
```
    contentSecurityPolicy: {
      'default-src': "'none'",
      'child-src': "'self'",
      'script-src': "'self' 'unsafe-inline' 'unsafe-eval'",
      'font-src': "'self'",
      'connect-src': "'self'",
      'img-src': "'self'",
      'style-src': "'self' 'unsafe-inline'",
      'frame-src': "'none'"
    }
```
[It's reveal now some other issues] (https://gist.github.com/Axxon/94e5a1edd66c1e168923)

I push my code on [github] (https://github.com/Axxon/ember-menu-test), could you take a look on ? thanks you very much for you help.

**Comment by ritesh83** [comment]
Just refer to the link in your deprecation warnings to fix the problem.
http://emberjs.com/deprecations/v1.x/#toc_deprecate-access-to-instances-in-initializers

**Comment by Axxon** [comment]
(hellooooo)
Let me (or you) first resolve the problem before close this issue. In theory a deprecated alert is not suppose to break the process ... Next, the deprecated method could come from a dependency so in this case of a empty project, just your bundle see my github, what should i do. 
If you seen my code, there just minimal code to display my fixture menu entries, but nothing is appear in /category.
 ... deprecated ?
Ok let see:
in console log > at ember$data$lib$initializers$store$$initializeStore (http://localhost:4200/assets/vendor.js:70540:48)
in the code > registry.register('store:main', registry.lookupFactory('store:application') ...
i search that in the project code
there is 3 occurence in bower_components/ember-data
Sure i will not begin my first project with ember on the fixing of ember-data.

Conclusion it's not so easy and i've no idea how to fix that.

**Comment by yectep** [comment]
I'm not sure why you're asking this here if it's an issue with ember-data. This repo is just for the addon to add jsTree functionality for your project...

If you created an empty project without this addon and the warnings are still there, please ask the [ember-data](https://github.com/emberjs/data) authors.

**Comment by Axxon** [comment]
Thanks for the response, yes we understood that first content-policy and ember-data are problems that not concern directly this add-on. The problem with ember-data is in resolution now.
I said that i wanted to understand why nothing is displaying with the installation of your addon, the construction of a basic model and a view. Could you please tell me if i done a mistake in the minimal test code to display properly some categories [https://github.com/Axxon/ember-menu-test] (here).
