### ISSUE TITLE
Ember.Test Dependency

### ISSUE THREAD

**Issue by gregjopa** [ritesh83/ember-cli-jstree#15]
Thanks for the awesome addon. I just started using it today and it is flexible and nicely documented.

I ran into a problem with this addon in my ember-cli app when I do a production build with `ember build --environment production`.  It produces the following error: "Uncaught TypeError: Cannot read property 'registerWaiter' of undefined"

The problem is this component now depends on Ember.Test in this recent commit: https://github.com/ritesh83/ember-cli-jstree/commit/dd8101e0f3ae8359754b10095bc4c96d3761ebe2. I don't think Ember.Test is available by default when building an ember-cli app for production. Why does this addon need to depend on Ember.Test?

**Comment by gregjopa** [comment]
Also, here's my environment:

ember-cli: 0.2.3
ember: 1.11.1

**Comment by ritesh83** [comment]
@gregjopa You are right. I'll add a check. Should only perform that for the test environment.

**Comment by gregjopa** [comment]
Great, thanks @ritesh83. Please let me know when you publish a new version with this fix.

**Comment by ritesh83** [comment]
@gregjopa Just published a new version. Should work now.

**Comment by gregjopa** [comment]
Just tested v0.0.18 and it works great. Thanks for the fix!
