### ISSUE TITLE
Prototype use in Ember Addon

### ISSUE THREAD

**Issue by Dynasty9** [ritesh83/ember-cli-jstree#16]
Ember addon should have `extend_prototypes : false`.
```EmberENV: {
        EXTEND_PROTOTYPES : false,
}```
define('ember-component-inbound-actions/inbound-actions', ['exports', 'ember', 'ember-component-inbound-actions/action-proxy'], function (exports, Em, ActionProxy) {

```
  exports['default'] = Em['default'].Mixin.create({
    _inbound_actions_setup: function() {
      var proxy = ActionProxy['default'].create({
        target: this
      });

      this.set('actionReceiver', proxy);
    }.on('init') <---
  });
```
Can be converted to:
```
Ember.on('init', _inbound_actions_setup : function()
{
    ...
});

I can go through and fix and submit a PR if you agree.

**Comment by ritesh83** [comment]
@Dynasty9 Yes we should disable the extend_prototypes. Go ahead and submit a PR. I'll merge it in. Thanks.

**Comment by yectep** [comment]
@ritesh83 #18 should fix this
