### ISSUE TITLE
actionReceiver is null

### ISSUE THREAD

**Issue by TommyLike** [ritesh83/ember-cli-jstree#17]
My environment version is as below:
version: 1.13.1
node: 0.12.4
npm: 2.12.1
when ember-cli-jstree is installed, I use the component in this way:
```
//hbs file
{{ember-jstree
  actionReceiver=jstreeActionReceiver
  data=data
  eventDidBecomeReady="handleTreeDidBecomeReady"
  }}
```
and
```
//controller
App.MyController = Ember.Controller.extend({
jstreeActionReceiver: null,
data:[],
action:{
handleTreeDidBecomeReady:function(){
      console.log(this.get('jstreeActionReceiver'));       
      }
}
})
```
the jstreeActionReceiver is null,So what the mistake I have made?

**Comment by ritesh83** [comment]
Hi @TommyLike, ember-cli-jstree uses the 'ember-component-inbound-actions' addon and that has an issue with ember 1.13 https://github.com/GavinJoyce/ember-component-inbound-actions/issues/6

**Comment by HerveSeger** [comment]
Hi.
Any update on this issue?

I am having the same issue with ember 1.13.10.
Even more weird, the `selectedNodes` property is populated with the previous state of the tree. I need to use `this.get( 'jsTreeObject' ).jstree( true ).get_selected( true )` in `handleTreeEventDidChange` to retrieve the correct list of selected nodes.

I am confused :grimacing:

**Comment by HerveSeger** [comment]
Update:

Do not declare `jsTreeActionReceiver` in your controller because it overrides what ember-jstree defines and then you will be able to send actions as described in the documentation:
``` html
<div class="sample-tree col-sm-10">
	{{ember-jstree
		id = "activityTree"
		data = jsTreeData
		plugins = "checkbox"
		themes = jstreeTheme
		treeObject = jsTreeObject
		actionReceiver=jsTreeActionReceiver
		eventDidBecomeReady="handleEventDidBecomeReady"
	}}
</div>
```

``` js
handleEventDidBecomeReady: function () {
			console.log( '===============>     T R E E   R E A D Y      <=================' );
            // Let's pre-select all nodes.
			this.get( 'jsTreeActionReceiver' ).send( 'selectAll' );
		},
```

**Comment by gep13** [comment]
@ritesh83 I am seeing this issue today when trying to set-up the destroy action.  Are there any known issues?  Thanks.
