### ISSUE TITLE
Contextmenu doesn't show up

### ISSUE THREAD

**Issue by JaroVDH** [ritesh83/ember-cli-jstree#20]
![screen shot 2015-08-13 at 10 39 05](https://cloud.githubusercontent.com/assets/6927640/9245850/bba09dcc-41a7-11e5-9d48-0369a6ef9db6.png)

Context menu isn't showing up in the dummy app.
Might be relevant that I'm on Chrome, OSX (Yosemite).

**Comment by ritesh83** [comment]
Thanks for reporting.
Version 0.1.1 should fix this issue.
