### ISSUE TITLE
Disable multiple selection

### ISSUE THREAD

**Issue by eddiesholl** [ritesh83/ember-cli-jstree#34]
I'm trying to disable multiple selection as per the example at https://www.jstree.com/docs/config/. It needs to be an item passed to the 'core' config element. I can't see a way to get it through, based on the options exposed to ember and then all the way through to the configObject ie https://github.com/ritesh83/ember-cli-jstree/blob/master/addon/components/ember-jstree.js.

Is there a workaround or trick I have missed?

**Comment by ritesh83** [comment]
Hi @eddiesholl looks like we missed that option. Can you provide a pull request? Thanks!

**Comment by ccarterc** [comment]
So how does one set core options with this pr?
