### ISSUE TITLE
Make tags & releases

### ISSUE THREAD

**Issue by cristinawithout** [ritesh83/ember-cli-jstree#4]
npm install installs from master. Thinks it already has the latest, because there's no new tags. But what it has installed is v0.0.10. ember build fails because package.json requires v0.0.11. Have to uninstall & reinstall.

**Comment by ritesh83** [comment]
Its going through a lot changes. 
Once its stable I'll make a tag. 
Most likely this Friday.

**Comment by yectep** [comment]
+1

**Comment by ritesh83** [comment]
Created a tag
