### ISSUE TITLE
Implement custom event listeners

### ISSUE THREAD

**Issue by barthalexander** [ritesh83/ember-cli-jstree#42]
Hi,
first of all, thank you for this nice Tool.
I tried to implement some event listeners, but this doesnt work. 
I used your code written in the Readme. 

Can You explain how and where to implement this one?

I know this is probably no issue.

**Comment by yectep** [comment]
Hi @barthalexander,

You can attach jsTree event listeners on the _setupEventListeners method in: ember-cli-jstree/addon/components/ember-jstree.js

If you follow the convention set with other events in that list, you'll see that we'll have Ember send an action back up, which you can define in: ember-cli-jstree/addon/mixins/ember-jstree-actions.js

Hope this helps!

**Comment by mashaember** [comment]
Hi @yectep 

I guess the question is how to implement not supported event without changing addon code.
For instance, for oveflowing node text, I want to show the full text on hovering the node. But the hover_node.jstree event is not supported by ember-cli-jstree. I can add action to my component as follows:
handleHoverTreeNode(node) {
    var treeObject = this.get('jstreeObject');
    treeObject.on('hover_node.jstree', function(e, data) {
        Ember.$("#" + data.node.id).prop('title', data.node.text );
    }.bind(this));
But how do I register the hover event with the jstree in hbs, like I do for supported events? Like here:
 {{ember-jstree
    data=dimTreeData
    eventDidBecomeReady="handleTreeBecomeReady"
    eventDidOpen="handleOpenTreeNode"
    eventDidSelectNode="handleSelectTreeNode"
    eventDidChange="handleChangeTreeNode"
    treeObject=jstreeObject
    themes=themes
    }}
Currently I just used supported eventDidBecomeReady event to listen on hover like this:
handleTreeBecomeReady(){
      // Set the tooltip on hover node after all nodes are finished loading
      console.log('handleTreeBecomeReady is received..');
      this.get('jstreeObject').on('hover_node.jstree', function(e, data){
        console.log('handleHoverTreeNode is received...');
        Ember.$("#" + data.node.id).prop('title', data.node.text );
      });
    }
but I don't think this is a correct way to achieve my goal. Would you please assist?

**Comment by ritesh83** [comment]
Hi @mashaember,

We will have to change the addon code to add support for jsTree hover events.
We can add that in the next release.

In the meantime, you can use the tooltips (a_attr property) to show the full text on hover.
You can refer to the README file for an example.

**Comment by mashaember** [comment]
Hi @yectep

Using a_attr in my JSON hash means to let my server handle the tooltip, while I want any "decoration" stuff to be handled by my client. It would be great if you could kindly add the support for hover event in the next release. In the meantime, does my workaround (using ready event to listen on hover) looks to awkward? I mean, do you see any pitfalls implementing it this way or may it lead to any jstree misbehaviour?
Thanks for all your help.

**Comment by yectep** [comment]
Hi @mashaember,

Sorry to not reply earlier. I made PR #47 for @ritesh83 to merge that adds support for 3 new actions, including hover_node, dehover_node, and select_node. The docs have also been updated.

This way, you should not have to use `eventDidBecomeReady` anymore to filter through the events, you can just bind `eventDidHoverNode` in the component to an Ember action of your writing now :)

**Comment by mashaember** [comment]
@yectep @ritesh83 

Wow, I'm super excited to thank you, guys, for this prompt assistance and consideration! Great day:)

**Comment by ritesh83** [comment]
@mashaember I've merged the PR, fixed the hover_node typo and bumped up the version.
Let us know if you run into any issues.
Thanks!

**Comment by mashaember** [comment]
@ritesh83 @yectep 

Everything works just perfect, thank you so much again!
