### ISSUE TITLE
Fastboot compatibility

### ISSUE THREAD

**Issue by Gaurav0** [ritesh83/ember-cli-jstree#43]
So we need to not import jstree bower dependency when in fastboot mode, and not invoke jquery outside `didInsertElement` hooks.

**Comment by ritesh83** [comment]
@Gaurav0 I can work on this sometime next week. If its urgent, feel free to provide a pull request. Thanks!

**Comment by acorncom** [comment]
Looks like this issue can be closed too

**Comment by ritesh83** [comment]
Yes
