### ISSUE TITLE
Add children per promise

### ISSUE THREAD

**Issue by Drujik** [ritesh83/ember-cli-jstree#49]
Hi, I'm new in Ember, and I have a little problem. 
I'm trying to create a tree, that on opening the node I will send request to the server, to get it's children.
I don't want to load whole tree in the beginning.
How can I do it?>
When I tried to do it, but what when I click on some node, I get response from server (children), but then whole the tree becomes only the tree of children
Sorry, if it is not the right place.

**Comment by wuarmin** [comment]
I would run the demo. There's an example of lazy-loading:

Demo

Both dynamic (AJAX loaded) and static examples are in the dummy demo.

    Clone this repo: git clone
    Install packages: npm install then bower install
    Run ember serve
    Visit the sample app at http://localhost:4200.

**Comment by Drujik** [comment]
The thing is that I'm trying to get children of specific node, when I expand this node.
And to get these children I call "store.queryRecord".
Now I have 2 problems:
   1. I want call "store.queryRecord" on the event of expand of the node. What event should I use?
   2. I still don't realize how do I use promise(thats' what returns from "store.queryRecord", not the real data)

**Comment by Drujik** [comment]
Or maybe you can tell me how I can override toggle_node method?

**Comment by Drujik** [comment]
Never mind, I found what was my problem.
Thanks

**Comment by wuarmin** [comment]
What was your problem?

**Comment by Drujik** [comment]
Wrong usage of promise... like I said I'm new in Ember

**Comment by PankajWorks** [comment]
@AlexLvovsky How you solved the problem. what was logic which you used?

**Comment by AlexLvovsky** [comment]
@PankajWorks, actually I don't remember. And I don't have an access to this project any more.
Sorry
