### ISSUE TITLE
Support new 'ember install' format

### ISSUE THREAD

**Issue by mattlindsey** [ritesh83/ember-cli-jstree#5]
ember install [addon-name] now is the correct way to install an add-on in ember-cli 0.2.3.

Using new syntax gives error: The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.

**Comment by yectep** [comment]
It looks like this is something ember-cli/ember-cli#3846 should fix.

>0.2.1 support should be added soon. I'll probably hold off on this PR until that Ember CLI `generate` fix is made.
