### ISSUE TITLE
Search plugin not working on Ember 2.10 (Glimmer 2)

### ISSUE THREAD

**Issue by supersabillon** [ritesh83/ember-cli-jstree#59]
Using Ember 2.10 and the search plugin with this option:
`searchOptions: {
    'show_only_matches' : true
  }
`

I'm getting the following error when testing the search feature:

`"Assertion Failed: You modified searchTerm twice on <my-app-name@controller:application::ember294> in a single render. This was unreliable and slow in Ember 1.x and is no longer supported. See https://github.com/emberjs/ember.js/issues/13948 for more details."`

Related to this Glimmer 2 update: https://github.com/emberjs/ember.js/issues/13948

**Comment by supersabillon** [comment]
Upgraded addon to 2.10 and it works. I'm probably doing something wrong on my end. Closing issue.

**Comment by supersabillon** [comment]
Had to reopen since the issue does show up 2.10. The example of Dummy App just didn't reproduce it, but I was able to reproduce with this twiddle:

https://ember-twiddle.com/495bae1d9e8f537761388d94d7c50f1f?openFiles=controllers.application.js%2C

Try using the search feature and checkout the error in the console.

**Comment by ritesh83** [comment]
Thanks @supersabillon for reporting and fixing the issue. I merged your PR.

**Comment by acorncom** [comment]
Looks like this issue can be closed?

**Comment by ritesh83** [comment]
Yes
