### ISSUE TITLE
[Deprecation] document.registerElement is deprecated and will be removed in M73, around March

### ISSUE THREAD

**Issue by david-duncan** [ritesh83/ember-cli-jstree#93]
jstree has updated to 3.3.7 to fix this, https://github.com/vakata/jstree/issues/2165

package slider already allows this, just need to update and release a new version

**Comment by edprats** [comment]
Yup, looks like the new jstree fixes the deprecation. Is there a way to upgrade just the jstree addon?

**Comment by anilgupta83** [comment]
wouldn't this break compatibility with Edge?
window.customElement is not supported in IE/Edge
https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define#Browser_compatibility
